version: "3.8"
services:
  fastapi_server:
    build:
      context: .
      dockerfile: model/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./model:/app/model
  telegram_bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    env_file:
      - .env
    volumes:
      - ./bot:/app/bot
    depends_on:
      - fastapi_server
    command: sh -c "sleep 5 && python bot/bot.py"