name: Run Python tests

on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Start FastAPI server
        run: python -m fastapi run .\model\model_api_wrapped.py &
      - name: Run Tests
        env:
          TOKEN: ${{ secrets.TOKEN }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pytest .
